# Generated by Django 3.0.1 on 2020-06-15 19:49

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200615_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='letter',
            field=models.FileField(blank=True, upload_to=users.validators.directory_path_for_ref_letter, validators=[users.validators.validate_file_extension]),
        ),
    ]
