# Generated by Django 3.0.1 on 2020-06-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200616_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_1', to='users.Reference'),
        ),
    ]
