# Generated by Django 3.0.1 on 2020-06-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200616_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref_1_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_1_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_1_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_1_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_2_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_2_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_2_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_2_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_3_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_3_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_3_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_3_sent',
        ),
    ]
